spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:postgresql://localhost:5432/code-grade"
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always